### ISSUE TITLE
Can't get outgoing calls graph

### ISSUE THREAD

**Issue by nkelly1322** [beicause/call-graph#9] opened 2022-11-07 18:07 UTC
I get a complete incoming calls graph, but no outgoing.  Whenever I attempt to create an outgoing calls graph I get a graph with only 1 node, the call I tried to originate from.

Using clang language server with a compile_commands.json made from Bear Intercept-Build

Any notion of how I could fix/troubleshoot this?

**Comment by beicause** [comment] 2023-10-26 11:37
Duplicate of #1, #7,  #11

**Closed by beicause** 2023-10-26 11:37 UTC
